name: sync-releases-biblequiz
on:
  workflow_dispatch:
  release:
    types: [prereleased, released, deleted, unpublished]
jobs:
  sync-release:
    uses: biblequiz/BibleQuiz.com/.github/workflows/sync-release-template.yml@main
    with:
      product_name: SeasonPacks
      commit_changes: true
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
